// Code generated by protoc-gen-go.
// source: cat/cat.proto
// DO NOT EDIT!

/*
Package cat is a generated protocol buffer package.

It is generated from these files:
	cat/cat.proto

It has these top-level messages:
	Cat
*/
package cat

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Cat struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	TailLength   int32  `protobuf:"varint,2,opt,name=tail_length" json:"tail_length,omitempty"`
	FavoriteFood string `protobuf:"bytes,3,opt,name=favorite_food" json:"favorite_food,omitempty"`
}

func (m *Cat) Reset()         { *m = Cat{} }
func (m *Cat) String() string { return proto.CompactTextString(m) }
func (*Cat) ProtoMessage()    {}

func init() {
}
